#somas, string, int e float
s = str(input('Digite uma string s: '))
i = int(input('Digite um inteiro i: '))
r = float(input('Digite um real r: '))
print('s+s = ' + f'{s+s}')
print('i+i = ' + f'{i+i}')
print('r+r = ' + f'{r+r}')
print('i*s = ' + f'{i*s}')
print('i*i = ' + f'{i*i}')
print('i*r = ' + f'{i*r}')
print('r/i = ' + f'{r/i}')
print('2*i/i = ' + f'{2*i/i}')
print('i/i*2 = ' + f'{i/i*2}')
